name: rapids
channels:
  - conda-forge
  - rapidsai
  - nvidia
dependencies:
  - python=3.11
  - cudf=24.04 
  - cuml=24.04
  - cuda-version=12.3
  - black
  - tqdm
  - h5py
  - polars
  - matplotlib
  - gdown
  - pyyaml
  - mypy
  - uniplot
  - wandb
  - flask
  - jsonschema
  - seaborn
  - aeon
  - sktime