datasets:
  - AtrialFibrillation
  - ArticularyWordRecognition
  - BasicMotions
  - Cricket
  - DuckDuckGeese
  - ERing
  - Epilepsy
  - EigenWorms
  - EthanolConcentration
  - FingerMovements
  - Handwriting
  - HandMovementDirection
  - Heartbeat
  - JapaneseVowels
  - LSST
  - Libras
  - MotorImagery
  - NATOPS
  - PEMS-SF
  - Phoneme
  - RacketSports
  - SelfRegulationSCP1
  - SelfRegulationSCP2
  - StandWalkJump
  - SpokenArabicDigits
  - UWaveGestureLibrary
models:
  - RNN
  - RNNTime2Vec
  - RNNPos
  - RNNtPos
  - RNNLinear
  - RNNDelta
  - RNNTime2VecDelta
  - RNNPosDelta
  - RNNtPosDelta
  - RNNLinearDelta
  - Transformer
  - TransformerTime2Vec
  - TransformerPos
  - TransformertPos
  - TransformerLinear
  - TransformerDelta
  - TransformerTime2VecDelta
  - TransformerPosDelta
  - TransformertPosDelta
  - TransformerLinearDelta
  # - RidgeClassifier
  # - CanonicalIntervalForest
  # - HIVECOTEV2
  # - ResNetClassifier
pmisses:
  - 0.0
  - 0.2
  - 0.4
  - 0.6
  - 0.7
  - 0.8
  - 0.9
torch_tester:
  loss: CrossEntropyLoss
  batch_size: 10
  base_path: data/outputs
  inf_sample_size: 10
general_tester:
  base_path: data/outputs
  add_encoding: false
  time_encoding_size: 50
  dropout: 0.0