datasets:
  - Car
  - CinCECGTorso
  - Computers
  - Earthquakes
  - ECG200
  - Fish
  - FordA
  - InlineSkate
  - OSULeaf
  - PowerCons
  - RefrigerationDevices
  - ScreenType
  - Symbols
  - ToeSegmentation1
  - Wafer
  # - ArticularyWordRecognition
  # - BasicMotions
  # - Cricket
  # - ERing
  # - Epilepsy
  # - Heartbeat
  # - JapaneseVowels
  # - LSST
  # - Libras
  # - NATOPS
  # - PEMS-SF
  # - RacketSports
  # - SelfRegulationSCP1
  # - SpokenArabicDigits
  # - UWaveGestureLibrary

models:
  - RNN
  - RNNTime2Vec
  - RNNPE
  - RNNTPE
  - RNNLinear
  - RNNTime2VecRel
  - RNNPERel
  - RNNTPERel
  - RNNLinearRel
  - RNNTimestamps
  - RNNTimestampsRel
  - TransformerTimestamps
  - TransformerTimestampsRel
  - Transformer
  - TransformerTime2Vec
  - TransformerPE
  - TransformerTPE
  - TransformerLinear
  - TransformerTime2VecRel
  - TransformerPERel
  - TransformerTPERel
  - TransformerLinearRel
  # - RidgeClassifier
  # - CanonicalIntervalForest
  # - HIVECOTEV2
  # - ResNetClassifier
pmisses:
  - 0.0
  - 0.2
  - 0.4
  - 0.6
  - 0.7
  - 0.8
  - 0.9
torch_tester:
  loss: CrossEntropyLoss
  batch_size: 10
  base_path: data/outputs
  inf_sample_size: 10
general_tester:
  base_path: data/outputs
  add_encoding: false
  time_encoding_size: 50
  dropout: 0.0