datasets:
  - ERing
  - Epilepsy
  - Heartbeat
  - UWaveGestureLibrary
  - ArticularyWordRecognition
  - EthanolConcentration
  - Libras
  - AsphaltPavementTypeCoordinates
  - FingerMovements
  - Handwriting
models:
  # - TSCRNNRel
  # - TSCRNNAbs
  # - TSCRNNTimestamps
  # - TSCRNN
  - TSCRNNTime2Vec
  # - TSCTransformerRel
  # - TSCTransformerAbs
  # - TSCTransformerTimestamps
  # - TSCTransformer
  - TSCTransformerTime2Vec
  # - RidgeClassifier
  # - CanonicalIntervalForest
  # - HIVECOTEV2
  # - ResNetClassifier
pmisses:
  - 0.0
  - 0.2
  - 0.4
  - 0.6
  - 0.7
  - 0.8
  - 0.9
torch_tester:
  loss: CrossEntropyLoss
  batch_size: 10
  base_path: data/outputs
  inf_sample_size: 10
general_tester:
  base_path: data/outputs
  add_encoding: false
  time_encoding_size: 50
  dropout: 0.0