datasets:
  - ArticularyWordRecognition
  - BasicMotions
  - Cricket
  - ERing
  - Epilepsy
  - Heartbeat
  - JapaneseVowels
  - LSST
  - Libras
  - NATOPS
  - PEMS-SF
  - RacketSports
  - SelfRegulationSCP1
  - SpokenArabicDigits
  - UWaveGestureLibrary

models:
  - RNNTimestamps
  - RNNTimestampsDelta
  - TransformerTimestamps
  - TransformerTimestampsDelta
  - RNN
  - RNNTime2Vec
  - RNNPE
  - RNNTPE
  - RNNLinear
  - RNNDelta
  - RNNTime2VecDelta
  - RNNPEDelta
  - RNNTPEDelta
  - RNNLinearDelta
  - Transformer
  - TransformerTime2Vec
  - TransformerPE
  - TransformerTPE
  - TransformerLinear
  - TransformerDelta
  - TransformerTime2VecDelta
  - TransformerPEDelta
  - TransformerTPEDelta
  - TransformerLinearDelta
  # - RidgeClassifier
  # - CanonicalIntervalForest
  # - HIVECOTEV2
  # - ResNetClassifier
pmisses:
  - 0.0
  - 0.2
  - 0.4
  - 0.6
  - 0.7
  - 0.8
  - 0.9
torch_tester:
  loss: CrossEntropyLoss
  batch_size: 10
  base_path: data/outputs
  inf_sample_size: 1
general_tester:
  base_path: data/outputs
  add_encoding: false
  time_encoding_size: 50
  dropout: 0.0