datasets:
  - ERing
  - Epilepsy
  - Heartbeat
  - UWaveGestureLibrary
  - ArticularyWordRecognition
  - EthanolConcentration
  - Libras
  - AsphaltPavementTypeCoordinates
  - FingerMovements
  - Handwriting
models:
  - TSClassifier
  # - RidgeClassifier
  # - CanonicalIntervalForest
  # - HIVECOTEV2
  # - ResNetClassifier
  
torch_trainer:
  loss: CrossEntropyLoss
  n_epochs: 500
  batch_size: 8
  early_stop: true
  tol: 1e-4
  lr: 1e-3
  snapshot_interval: 10
  base_path: data/models

general_trainer:
  base_path: data/models