datasets:
  - ERing
  - Epilepsy
  - Heartbeat
  - UWaveGestureLibrary
  - ArticularyWordRecognition
  - EthanolConcentration
  - Libras
  - AsphaltPavementTypeCoordinates
  - FingerMovements
  - Handwriting
models:
  # - TSCRNNRel
  # - TSCRNNAbs
  # - TSCRNNTimestamps
  # - TSCRNN
  - TSCRNNTime2Vec
  # - TSCTransformerRel
  # - TSCTransformerAbs
  # - TSCTransformerTimestamps
  # - TSCTransformer
  - TSCTransformerTime2Vec
  # - RidgeClassifier
  # - CanonicalIntervalForest
  # - HIVECOTEV2
  # - ResNetClassifier
  
torch_trainer:
  classification_training:
    loss: CrossEntropyLoss
    n_epochs: 1000
    batch_size: 16
    early_stop: true
    tol: 1e-3
    lr: 1e-3
    patience: 200
    snapshot_interval: 10
    base_path: data/models

general_trainer:
  base_path: data/models
  add_encoding: false
  time_encoding_size: 50
  dropout: 0.0