datasets:
  - AsphaltPavementTypeCoordinates
models:
  - TSClassifier
deep_trainer:
  loss: CrossEntropyLoss
  n_epochs: 200
  batch_size: 20
  early_stop: true
  tol: 1e-3
  lr: 1e-3
  snapshot_interval: 10
  base_path: data/models

general_trainer: