datasets:
  - ERing
  - Epilepsy
  - Heartbeat
  - UWaveGestureLibrary
  - ArticularyWordRecognition
  - EthanolConcentration
  - Libras
  - AsphaltPavementTypeCoordinates
  - FingerMovements
  - Handwriting
models:
  - TSClassifier
  # - TSAREncoderDecoder
  # - RidgeClassifier
  # - CanonicalIntervalForest
  # - HIVECOTEV2
  # - ResNetClassifier
  
torch_trainer:
  classification_training:
    loss: CrossEntropyLoss
    n_epochs: 500
    batch_size: 32
    early_stop: true
    tol: 1e-3
    lr: 1e-3
    patience: 50
    snapshot_interval: 10
    base_path: data/models

general_trainer:
  base_path: data/models
  add_encoding: false
  time_encoding_size: 50
  dropout: 0.0